/**
 * M3 manual verification fixtures: an 18x18x10mm cube split down the middle
 * on X into Part A + Part B, written as real .stl files for the one thing
 * this session can't verify itself -- opening them in a real slicer. Run:
 *
 *   npx tsx scripts/generate-m3-split-fixtures.ts
 *
 * Output goes to fixtures/m3-split/. See the generated README.md there for
 * exactly what to check in Bambu Studio / OrcaSlicer / PrusaSlicer.
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { createCubeMesh } from "../src/primitives/cube.js";
import { exportSTLBinary } from "../src/stl.js";
import { computeBoundingBox, computeSignedVolume, triangleCount } from "../src/mesh.js";
import { validateMesh } from "../src/validate.js";
import { createBooleanEngine } from "../src/boolean.js";

const outDir = join(dirname(fileURLToPath(import.meta.url)), "..", "fixtures", "m3-split");
mkdirSync(outDir, { recursive: true });

function write(name: string, buffer: ArrayBuffer) {
  writeFileSync(join(outDir, name), Buffer.from(buffer));
}

const original = createCubeMesh(18, 18, 10);
const originalBox = computeBoundingBox(original);
const originalVolume = Math.abs(computeSignedVolume(original));

const engine = await createBooleanEngine();
// normal (1,0,0), offset 0 -> plane x=0, cuts the 18mm X span exactly in half
const [partA, partB] = engine.splitByPlane(original, [1, 0, 0], 0);

const reportA = validateMesh(partA);
const reportB = validateMesh(partB);
const boxA = computeBoundingBox(partA);
const boxB = computeBoundingBox(partB);
const volA = Math.abs(computeSignedVolume(partA));
const volB = Math.abs(computeSignedVolume(partB));

write("original_18x18x10.stl", exportSTLBinary(original, "original_18x18x10"));
write("part_a.stl", exportSTLBinary(partA, "part_a"));
write("part_b.stl", exportSTLBinary(partB, "part_b"));

const notes = `# M3 Plane Split -- manual Bambu Studio verification

Generated by `+"`scripts/generate-m3-split-fixtures.ts`"+`. An 18x18x10mm cube,
split down the middle on X (cutting plane x=0), the same operation the app's
Split panel performs (Center to Object, then Rotate the plane so its normal
points along X). All units mm, 1 world unit = 1mm throughout.

## original_18x18x10.stl
Expect bounding box exactly **18 x 18 x 10 mm**.
Triangles: ${triangleCount(original)}. Volume: ${originalVolume.toFixed(2)} mm^3.

## part_a.stl
Expect bounding box **${boxA.size[0].toFixed(3)} x ${boxA.size[1].toFixed(3)} x ${boxA.size[2].toFixed(3)} mm**
(should read as ~9 x 18 x 10mm).
Triangles: ${triangleCount(partA)}. Watertight: ${reportA.isWatertight}. Volume: ${volA.toFixed(2)} mm^3.

## part_b.stl
Expect bounding box **${boxB.size[0].toFixed(3)} x ${boxB.size[1].toFixed(3)} x ${boxB.size[2].toFixed(3)} mm**
(should read as ~9 x 18 x 10mm).
Triangles: ${triangleCount(partB)}. Watertight: ${reportB.isWatertight}. Volume: ${volB.toFixed(2)} mm^3.

## What to check in the slicer

1. **original_18x18x10.stl** alone: bounding box reads 18 x 18 x 10mm, not
   180x180x100 or 18000x18000x10000 -- confirms no x10/x1000 scale error.
2. **part_a.stl** and **part_b.stl** loaded together in the SAME project,
   without moving either one: they should sit flush against each other with
   no gap and no overlap, together reconstructing the original 18x18x10mm
   block at the same plate position (both parts were exported with their
   design-space coordinates baked in directly -- neither was recentered).
3. Both parts should slice without repair/manifold warnings from the slicer
   (they were validated watertight before export: Part A ${reportA.isWatertight ? "PASS" : "FAIL"}, Part B ${reportB.isWatertight ? "PASS" : "FAIL"}).
4. Volume sanity: Part A + Part B volume (${(volA + volB).toFixed(2)} mm^3) should
   equal the original's volume (${originalVolume.toFixed(2)} mm^3) to within
   float rounding.
`;

writeFileSync(join(outDir, "README.md"), notes);
console.log(`Wrote fixtures to ${outDir}`);
console.log(`Part A bbox: ${JSON.stringify(boxA.size)}, watertight=${reportA.isWatertight}`);
console.log(`Part B bbox: ${JSON.stringify(boxB.size)}, watertight=${reportB.isWatertight}`);
console.log(`Volume check: original=${originalVolume.toFixed(2)} A+B=${(volA + volB).toFixed(2)}`);
