/**
 * Generates real .stl files for the one manual verification step this
 * package cannot automate: opening a file in an actual slicer (Bambu
 * Studio / OrcaSlicer / PrusaSlicer) and confirming the dimensions shown
 * there match what was requested here. Run with:
 *
 *   npx tsx scripts/generate-fixtures.ts
 *
 * Output goes to fixtures/manual-verification/. See the generated README.md
 * there for exactly what to check.
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { createCubeMesh } from "../src/primitives/cube.js";
import { createCylinderMesh } from "../src/primitives/cylinder.js";
import { exportNodeAsSTL, exportSTLBinary } from "../src/stl.js";
import { applyTransformToMesh, type Transform } from "../src/transform.js";
import { computeBoundingBox, computeSignedVolume } from "../src/mesh.js";
import { validateMesh } from "../src/validate.js";
import { createBooleanEngine } from "../src/boolean.js";

const outDir = join(dirname(fileURLToPath(import.meta.url)), "..", "fixtures", "manual-verification");
mkdirSync(outDir, { recursive: true });

const notes: string[] = [];
notes.push("# Manual STL verification fixtures");
notes.push("");
notes.push("Generated by `scripts/generate-fixtures.ts`. Open each file in Bambu Studio");
notes.push("(or OrcaSlicer/PrusaSlicer) and confirm the reported size matches the expected");
notes.push("value below. All units are millimeters -- this checks that geometry-core's");
notes.push("`1 world unit = 1mm` convention survives the real STL export path unchanged.");
notes.push("");

function write(name: string, buffer: ArrayBuffer) {
  writeFileSync(join(outDir, name), Buffer.from(buffer));
}

// 1. cube 18x18x10mm, no transform
{
  const mesh = createCubeMesh(18, 18, 10);
  write("cube_18x18x10.stl", exportSTLBinary(mesh, "cube_18x18x10"));
  notes.push("## cube_18x18x10.stl");
  notes.push("Expect bounding box exactly **18 x 18 x 10 mm** in the slicer.");
  notes.push("");
}

// 2. cylinder diameter 14mm, height 20mm
{
  const mesh = createCylinderMesh(14, 20, 64);
  write("cylinder_d14.stl", exportSTLBinary(mesh, "cylinder_d14"));
  notes.push("## cylinder_d14.stl");
  notes.push("Expect bounding box exactly **14 x 14 x 20 mm** (X/Y diameter x height).");
  notes.push("64 radial segments, so the polygon-vs-true-circle diameter error is negligible.");
  notes.push("");
}

// 3. object with translate + rotate
{
  const local = createCubeMesh(18, 18, 10);
  const design: Transform = { position: [37.5, -12, 8], rotationDeg: [0, 0, 30], scale: [1, 1, 1] };
  write("translated_rotated_cube.stl", exportNodeAsSTL(local, design, null, "translated_rotated_cube"));
  notes.push("## translated_rotated_cube.stl");
  notes.push("18x18x10mm cube, design transform = position (37.5, -12, 8)mm, rotate 30deg about Z.");
  const worldMesh = applyTransformToMesh(local, design);
  const box = computeBoundingBox(worldMesh);
  notes.push(
    `Expect bounding box approx **${box.size[0].toFixed(2)} x ${box.size[1].toFixed(2)} x ${box.size[2].toFixed(2)} mm** ` +
      "(footprint widened by the 30deg rotation; height unchanged). " +
      "The point of this fixture is confirming the *position* in the slicer's build plate " +
      "matches (centroid roughly at X=37.5, Y=-12, Z=8 from plate origin, modulo the slicer's own origin convention) " +
      "-- i.e. the transform was baked into the file, not lost.",
  );
  notes.push("");
}

// 4. boolean split proof-of-concept: two parts that must line up when loaded together
{
  const engine = await createBooleanEngine();
  const localMesh = createCubeMesh(20, 20, 40);
  const design: Transform = { position: [10, 5, 0], rotationDeg: [0, 0, 0], scale: [1, 1, 1] };
  const worldMesh = applyTransformToMesh(localMesh, design);
  const [partA, partB] = engine.splitByPlane(worldMesh, [0, 0, 1], 0);

  const reportA = validateMesh(partA);
  const reportB = validateMesh(partB);
  const volume = Math.abs(computeSignedVolume(worldMesh));

  write("split_part_a.stl", exportSTLBinary(partA, "split_part_a"));
  write("split_part_b.stl", exportSTLBinary(partB, "split_part_b"));

  notes.push("## split_part_a.stl + split_part_b.stl");
  notes.push(
    "A 20x20x40mm cube (positioned at design X=10, Y=5) split in half by the Z=0 plane. " +
      "**Import both files into the same slicer project without moving either one** -- " +
      "they should sit flush against each other and reconstruct one 20x20x40mm block " +
      "at the same plate position, with no gap and no overlap.",
  );
  notes.push(
    `Part A: watertight=${reportA.isWatertight}, open edges=${reportA.openEdgeCount}, non-manifold edges=${reportA.nonManifoldEdgeCount}.`,
  );
  notes.push(
    `Part B: watertight=${reportB.isWatertight}, open edges=${reportB.openEdgeCount}, non-manifold edges=${reportB.nonManifoldEdgeCount}.`,
  );
  notes.push(`Combined volume should read as ~${volume.toFixed(0)} mm^3 total in the slicer if it reports part volumes.`);
  notes.push("");
}

writeFileSync(join(outDir, "README.md"), notes.join("\n"));
console.log(`Wrote fixtures to ${outDir}`);
